/* 1. CREATE THE DATABASE*/
CREATE DATABASE CCDB;
USE CCDB;
/* 2. IMPORT THE TABLE FROM CSV TO SQL WITH THE NAME {CC_DETAILS} WHICH REPRESENT THE CREDIT CARD DETAILS */
SELECT * FROM CC_DETAILS;
/* 3. IMPORT THE TABLE FROM CSV TO SQL WITH THE NAME {CUST_DETAILS} WHICH REPRESENT THE CUSTOMER DETAILS */
SELECT * FROM CUST_DETAILS;

dROP TABLE CUST_DETAILS;